# Generated by Django 3.2.8 on 2025-01-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('message', models.TextField()),
                ('accept_terms', models.BooleanField(default=False)),
                ('accept_marketing_emails', models.BooleanField(default=False)),
            ],
        ),
    ]
