# Generated by Django 3.2.8 on 2025-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20250103_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
    ]
