# Generated by Django 3.2.8 on 2025-01-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travello.guide'),
            preserve_default=False,
        ),
    ]
