# Generated by Django 3.2.8 on 2025-01-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_booking_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
