# Generated by Django 3.2.8 on 2025-01-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_guide_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user',
        ),
    ]
