# Generated by Django 3.2.8 on 2025-01-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_remove_guide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='list_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
