# Generated by Django 3.2.8 on 2025-01-02 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_auto_20250102_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
